/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SorularRouteImport } from './routes/sorular'
import { Route as HostCodeRouteImport } from './routes/host.$code'
import { Route as PlayCodeRouteImport } from './routes/play.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorularRoute = SorularRouteImport.update({
  id: '/sorular',
  path: '/sorular',
  getParentRoute: () => rootRouteImport,
} as any)
const HostCodeRoute = HostCodeRouteImport.update({
  id: '/host/$code',
  path: '/host/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sorular': typeof SorularRoute
  '/host/$code': typeof HostCodeRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sorular': typeof SorularRoute
  '/host/$code': typeof HostCodeRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sorular': typeof SorularRoute
  '/host/$code': typeof HostCodeRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sorular' | '/host/$code' | '/play/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sorular' | '/host/$code' | '/play/$code'
  id: '__root__' | '/' | '/sorular' | '/host/$code' | '/play/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SorularRoute: typeof SorularRoute
  HostCodeRoute: typeof HostCodeRoute
  PlayCodeRoute: typeof PlayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorular': {
      id: '/sorular'
      path: '/sorular'
      fullPath: '/sorular'
      preLoaderRoute: typeof SorularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$code': {
      id: '/host/$code'
      path: '/host/$code'
      fullPath: '/host/$code'
      preLoaderRoute: typeof HostCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SorularRoute: SorularRoute,
  HostCodeRoute: HostCodeRoute,
  PlayCodeRoute: PlayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
